---
- name: Configure Syzkaller
  hosts: Security

  gather_facts: no
  tasks:
    - name: Copy Syzkaller configuration file
      ansible.builtin.copy:
        content: |
          {
            "target": "linux/amd64",
            "http": "0.0.0.0:56741",
            "workdir": "/home/crabsnk/Desktop/syzkaller/workdir",
            "kernel_obj": "/home/crabsnk/Desktop/linux/linux-6.6.23",
            "image": "/home/crabsnk/Desktop/linux/linux-6.6.23/img/bullseye.img",
            "sshkey": "/home/crabsnk/Desktop/linux/linux-6.6.23/img/bullseye.id_rsa",
            "syzkaller": "/home/crabsnk/Desktop/syzkaller",
            "procs": 8,
            "type": "qemu",
            "vm": {
              "count": 4,
              "kernel": "/home/ansible/Kernel/arch/x86/boot/bzImage",
              "cpu": 2,
              "mem": 2048
            }	
	"enable_syscalls": [
		"openat$apparmor_task_current",
		"openat$apparmor_thread_current",
		"write$apparmor_current",
		"openat$apparmor_task_exec",
		"openat$apparmor_thread_exec",
		"write$apparmor_exec",
		"openat$selinux_load",
		"write$selinux_load",
		"openat$selinux_access",
		"openat$selinux_member",
		"openat$selinux_relabel",
		"write$selinux_access",
		"openat$selinux_context",
		"write$selinux_context",
		"openat$selinux_create",
		"write$selinux_create",
		"openat$selinux_validatetrans",
		"write$selinux_validatetrans",
		"openat$selinux_user",
		"write$selinux_user",
		"openat$selinux_enforce",
		"openat$selinux_commit_pending_bools",
		"openat$selinux_mls",
		"openat$selinux_checkreqprot",
		"openat$selinux_status",
		"openat$selinux_policy",
		"openat$selinux_avc_cache_stats",
		"openat$selinux_avc_cache_threshold",
		"openat$selinux_avc_hash_stats",
		"openat$selinux_attr",
		"write$selinux_attr",
		"setxattr$security_selinux",
		"lsetxattr$security_selinux",
		"fsetxattr$security_selinux"
	]
	          }
        dest: /home/ansible/config/driver.cfg
        owner: ansible
        group: ansible

    - name: Execute Syzkaller manager command
      ansible.builtin.command: /home/ansible/syzkaller/bin/syz-manager -config=/home/ansible/config/driver.cfg

